package danmaku

import (
	"compress/flate"
	"encoding/xml"
	"fmt"
	"io"
	"math"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

// DanmakuXML B站弹幕 XML 根结构
type DanmakuXML struct {
	XMLName xml.Name      `xml:"i"`
	D       []DanmakuItem `xml:"d"`
}

// DanmakuItem 单条弹幕
type DanmakuItem struct {
	P    string `xml:"p,attr"` // "time,mode,fontSize,color,timestamp,pool,userHash,dmid"
	Text string `xml:",chardata"`
}

// ParsedDanmaku 解析后的弹幕
type ParsedDanmaku struct {
	Time     float64 // 出现时间（秒）
	Mode     int     // 1/2/3=滚动, 4=底部, 5=顶部, 6=逆向, 7=精准, 8=高级
	FontSize int     // 字号
	Color    int64   // 十进制颜色
	Text     string
}

// DownloadDanmakuXML 下载弹幕 XML 到本地文件
func DownloadDanmakuXML(cid int64, outputPath string) error {
	// 主接口
	url := fmt.Sprintf("https://comment.bilibili.com/%d.xml", cid)

	client := &http.Client{Timeout: 30 * time.Second}
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36")
	req.Header.Set("Referer", "https://www.bilibili.com")
	req.Header.Set("Accept-Encoding", "deflate")

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("download danmaku: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return fmt.Errorf("danmaku HTTP %d", resp.StatusCode)
	}

	// B站弹幕接口可能返回 deflate 压缩
	var reader io.Reader
	if resp.Header.Get("Content-Encoding") == "deflate" {
		reader = flate.NewReader(resp.Body)
	} else {
		reader = resp.Body
	}

	data, err := io.ReadAll(reader)
	if err != nil {
		return fmt.Errorf("read danmaku body: %w", err)
	}

	return os.WriteFile(outputPath, data, 0644)
}

// ParseXML 解析弹幕 XML 文件
func ParseXML(xmlPath string) ([]ParsedDanmaku, error) {
	data, err := os.ReadFile(xmlPath)
	if err != nil {
		return nil, err
	}

	var dmXML DanmakuXML
	if err := xml.Unmarshal(data, &dmXML); err != nil {
		return nil, fmt.Errorf("parse danmaku xml: %w", err)
	}

	var result []ParsedDanmaku
	for _, d := range dmXML.D {
		parts := strings.Split(d.P, ",")
		if len(parts) < 4 {
			continue
		}
		t, _ := strconv.ParseFloat(parts[0], 64)
		mode, _ := strconv.Atoi(parts[1])
		fontSize, _ := strconv.Atoi(parts[2])
		color, _ := strconv.ParseInt(parts[3], 10, 64)

		result = append(result, ParsedDanmaku{
			Time:     t,
			Mode:     mode,
			FontSize: fontSize,
			Color:    color,
			Text:     strings.TrimSpace(d.Text),
		})
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].Time < result[j].Time
	})

	return result, nil
}

// XMLToASS 将弹幕 XML 转换为 ASS 字幕格式（兼容 Emby/Jellyfin/mpv）
func XMLToASS(xmlPath, assPath string, width, height int) error {
	danmakus, err := ParseXML(xmlPath)
	if err != nil {
		return err
	}

	if width <= 0 {
		width = 1920
	}
	if height <= 0 {
		height = 1080
	}

	f, err := os.Create(assPath)
	if err != nil {
		return err
	}
	defer f.Close()

	// ASS 头部
	fmt.Fprintf(f, "[Script Info]\n")
	fmt.Fprintf(f, "; Script generated by video-subscribe-dl danmaku converter\n")
	fmt.Fprintf(f, "Title: Bilibili Danmaku\n")
	fmt.Fprintf(f, "ScriptType: v4.00+\n")
	fmt.Fprintf(f, "PlayResX: %d\n", width)
	fmt.Fprintf(f, "PlayResY: %d\n", height)
	fmt.Fprintf(f, "Aspect Ratio: %d:%d\n", width, height)
	fmt.Fprintf(f, "Collisions: Normal\n")
	fmt.Fprintf(f, "WrapStyle: 2\n")
	fmt.Fprintf(f, "ScaledBorderAndShadow: yes\n")
	fmt.Fprintf(f, "YCbCr Matrix: TV.601\n\n")

	// 样式定义
	fontSize := height / 27 // 基准字号
	fmt.Fprintf(f, "[V4+ Styles]\n")
	fmt.Fprintf(f, "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
	fmt.Fprintf(f, "Style: R2L,Microsoft YaHei,%d,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,8,0,0,0,1\n", fontSize)
	fmt.Fprintf(f, "Style: TOP,Microsoft YaHei,%d,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,8,0,0,0,1\n", fontSize)
	fmt.Fprintf(f, "Style: BTM,Microsoft YaHei,%d,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,2,0,0,0,1\n\n", fontSize)

	// 弹幕事件
	fmt.Fprintf(f, "[Events]\n")
	fmt.Fprintf(f, "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")

	// 碰撞检测：跟踪每行的结束时间
	scrollDuration := 12.0 // 滚动弹幕持续秒数
	fixedDuration := 5.0   // 固定弹幕持续秒数

	maxScrollRows := height / (fontSize + 4)
	maxFixedRows := height / 3 / (fontSize + 4)

	scrollRowEnd := make([]float64, maxScrollRows)
	topRowEnd := make([]float64, maxFixedRows)
	btmRowEnd := make([]float64, maxFixedRows)

	for _, dm := range danmakus {
		if dm.Text == "" {
			continue
		}
		// 跳过高级弹幕（mode 7, 8）
		if dm.Mode == 7 || dm.Mode == 8 {
			continue
		}

		// 颜色转换：十进制 -> ASS &HBBGGRR
		assColor := decColorToASS(dm.Color)

		// 字号缩放
		scale := 1.0
		if dm.FontSize == 18 {
			scale = 0.75
		} else if dm.FontSize == 36 {
			scale = 1.5
		}

		colorTag := ""
		if dm.Color != 16777215 { // 非白色
			colorTag = fmt.Sprintf("\\c%s", assColor)
		}
		scaleTag := ""
		if scale != 1.0 {
			fz := int(math.Round(float64(fontSize) * scale))
			scaleTag = fmt.Sprintf("\\fs%d", fz)
		}

		switch dm.Mode {
		case 1, 2, 3, 6: // 滚动弹幕（含逆向）
			row := findRow(scrollRowEnd, dm.Time)
			if row < 0 {
				continue // 屏幕满了，丢弃
			}
			scrollRowEnd[row] = dm.Time + scrollDuration

			startTime := formatASSTime(dm.Time)
			endTime := formatASSTime(dm.Time + scrollDuration)

			y := row*(fontSize+4) + fontSize/2

			// 滚动效果：从右到左（move）
			textWidth := len([]rune(dm.Text)) * fontSize // 粗略估算
			startX := width + textWidth/2
			endX := -textWidth / 2

			tags := fmt.Sprintf("{\\move(%d,%d,%d,%d)%s%s}", startX, y, endX, y, colorTag, scaleTag)
			fmt.Fprintf(f, "Dialogue: 0,%s,%s,R2L,,0,0,0,,%s%s\n", startTime, endTime, tags, escapeASS(dm.Text))

		case 5: // 顶部固定
			row := findRow(topRowEnd, dm.Time)
			if row < 0 {
				continue
			}
			topRowEnd[row] = dm.Time + fixedDuration

			startTime := formatASSTime(dm.Time)
			endTime := formatASSTime(dm.Time + fixedDuration)

			y := row*(fontSize+4) + fontSize/2

			tags := fmt.Sprintf("{\\an8\\pos(%d,%d)%s%s}", width/2, y, colorTag, scaleTag)
			fmt.Fprintf(f, "Dialogue: 0,%s,%s,TOP,,0,0,0,,%s%s\n", startTime, endTime, tags, escapeASS(dm.Text))

		case 4: // 底部固定
			row := findRow(btmRowEnd, dm.Time)
			if row < 0 {
				continue
			}
			btmRowEnd[row] = dm.Time + fixedDuration

			startTime := formatASSTime(dm.Time)
			endTime := formatASSTime(dm.Time + fixedDuration)

			y := height - row*(fontSize+4) - fontSize/2

			tags := fmt.Sprintf("{\\an2\\pos(%d,%d)%s%s}", width/2, y, colorTag, scaleTag)
			fmt.Fprintf(f, "Dialogue: 0,%s,%s,BTM,,0,0,0,,%s%s\n", startTime, endTime, tags, escapeASS(dm.Text))
		}
	}

	return nil
}

// findRow 找一个空闲行
func findRow(rowEnd []float64, currentTime float64) int {
	for i := range rowEnd {
		if currentTime >= rowEnd[i] {
			return i
		}
	}
	return -1
}

// decColorToASS 将十进制颜色(RGB)转为 ASS 格式 &HBBGGRR
func decColorToASS(color int64) string {
	r := (color >> 16) & 0xFF
	g := (color >> 8) & 0xFF
	b := color & 0xFF
	return fmt.Sprintf("&H%02X%02X%02X", b, g, r)
}

// formatASSTime 格式化为 ASS 时间 H:MM:SS.CC
func formatASSTime(seconds float64) string {
	if seconds < 0 {
		seconds = 0
	}
	h := int(seconds) / 3600
	m := (int(seconds) % 3600) / 60
	s := int(seconds) % 60
	cs := int((seconds - math.Floor(seconds)) * 100)
	return fmt.Sprintf("%d:%02d:%02d.%02d", h, m, s, cs)
}

// escapeASS 转义 ASS 中的特殊字符
func escapeASS(text string) string {
	text = strings.ReplaceAll(text, "\\", "\\\\")
	text = strings.ReplaceAll(text, "{", "\\{")
	text = strings.ReplaceAll(text, "}", "\\}")
	text = strings.ReplaceAll(text, "\n", "\\N")
	return text
}
